paths:
  /api/v1/genero:
    get:
      summary: Obtiene todos los géneros
      tags:
        - Genero
      responses:
        '200':
          description: Lista de géneros
        '500':
          description: Error del servidor
    post:
      summary: Crea un nuevo género
      tags:
        - Genero
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: "Masculino"
      responses:
        '201':
          description: Género creado
        '400':
          description: Datos inválidos

  /api/v1/genero/{id}:
    get:
      summary: Obtiene un género por ID
      tags:
        - Genero
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Género encontrado
        '404':
          description: Género no encontrado
    put:
      summary: Actualiza un género por ID
      tags:
        - Genero
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: "Femenino"
      responses:
        '200':
          description: Género actualizado
        '404':
          description: Género no encontrado
    delete:
      summary: Elimina (hard delete) un género por ID
      tags:
        - Genero
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Género eliminado
        '404':
          description: Género no encontrado
    patch:
      summary: Elimina (soft delete) un género por ID
      tags:
        - Genero
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Género marcado como eliminado
        '404':
          description: Género no encontrado

  /api/v1/genero/page/{pag}/{limit}:
    get:
      summary: Obtiene una página de géneros
      tags:
        - Genero
      parameters:
        - in: path
          name: pag
          required: true
          schema:
            type: integer
        - in: path
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: Página de géneros

  /api/v1/genero/deleted:
    get:
      summary: Obtiene todos los géneros eliminados (soft delete)
      tags:
        - Genero
      responses:
        '200':
          description: Lista de géneros eliminados

  /api/v1/genero/deleted/{id}:
    get:
      summary: Obtiene un género eliminado (soft delete) por ID
      tags:
        - Genero
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Género eliminado encontrado
        '404':
          description: Género no encontrado

  /api/v1/genero/deleted/page/{pag}/{limit}:
    get:
      summary: Obtiene una página de géneros eliminados (soft delete)
      tags:
        - Genero
      parameters:
        - in: path
          name: pag
          required: true
          schema:
            type: integer
        - in: path
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: Página de géneros eliminados
