paths:
  /api/v1/login:
    post:
      summary: Inicia sesión de un usuario
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email del usuario
                  example: user@example.com
                password:
                  type: string
                  description: Contraseña del usuario
                  example: stringPassword123
      responses:
        '200':
          description: Login exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  refreshToken:
                    type: string
        '401':
          description: Credenciales inválidas
        '500':
          description: Error del servidor
