paths:
  /api/v1/usuario:
    get:
      summary: Obtiene todos los usuarios
      tags:
        - Usuario
      responses:
        '200':
          description: Lista de usuarios
        '500':
          description: Error del servidor
    post:
      summary: Crea un nuevo usuario
      tags:
        - Usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: "John"
                apellido:
                  type: string
                  example: "Doe"
                email:
                  type: string
                  example: "john.doe@example.com"
                password:
                  type: string
                  example: "password123"
      responses:
        '201':
          description: Usuario creado
        '400':
          description: Datos inválidos

  /api/v1/usuario/{id}:
    get:
      summary: Obtiene un usuario por ID
      tags:
        - Usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Usuario encontrado
        '404':
          description: Usuario no encontrado
    put:
      summary: Actualiza un usuario por ID
      tags:
        - Usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                apellido:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: Usuario actualizado
        '404':
          description: Usuario no encontrado
    delete:
      summary: Elimina (hard delete) un usuario por ID
      tags:
        - Usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Usuario eliminado
        '404':
          description: Usuario no encontrado
    patch:
      summary: Elimina (soft delete) un usuario por ID
      tags:
        - Usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Usuario marcado como eliminado
        '404':
          description: Usuario no encontrado

  /api/v1/usuario/page/{pag}/{limit}:
    get:
      summary: Obtiene una página de usuarios
      tags:
        - Usuario
      parameters:
        - in: path
          name: pag
          required: true
          schema:
            type: integer
        - in: path
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: Página de usuarios

  /api/v1/usuario/deleted:
    get:
      summary: Obtiene todos los usuarios eliminados (soft delete)
      tags:
        - Usuario
      responses:
        '200':
          description: Lista de usuarios eliminados

  /api/v1/usuario/deleted/{id}:
    get:
      summary: Obtiene un usuario eliminado (soft delete) por ID
      tags:
        - Usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Usuario eliminado encontrado
        '404':
          description: Usuario no encontrado

  /api/v1/usuario/deleted/page/{pag}/{limit}:
    get:
      summary: Obtiene una página de usuarios eliminados (soft delete)
      tags:
        - Usuario
      parameters:
        - in: path
          name: pag
          required: true
          schema:
            type: integer
        - in: path
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: Página de usuarios eliminados
